buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
    // Opção usando a versão oficial mais recente publicada no Maven Central
    implementation 'org.opencv:opencv:4.9.0'

    // OU se estiver usando o com.github.quickbirdstudios / jitpack:
    // implementation 'com.github.quickbirdstudios:opencv-android:4.5.3.0'
}
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
