plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android' // Necessário se você estiver usando Kotlin no projeto
}

android {
    namespace 'com.example.botautoclicker'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.botautoclicker"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    // Configurações de compatibilidade para Java 8+
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    // Configuração para Kotlin (caso utilize arquivos .kt)
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    // Dependências de Suporte e UI Básicas
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    // Dependências para Testes
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
