plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bot.autoclicker'
    compileSdk 34

    defaultConfig {
        applicationId "com.bot.autoclicker"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    // Adicione a dependência do OpenCV aqui dentro:
    implementation 'com.github.quickbirdstudios:opencv-android:4.5.3.0'

    // Mantinha as outras dependências existentes do seu app (appcompat, material, etc.)
}
